# Generated by Django 5.1.2 on 2024-12-16 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enunciado",
                    models.CharField(
                        max_length=200, verbose_name="Enunciado da Pergunta"
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "curtidas",
                    models.IntegerField(default=0, verbose_name="Número de Curtidas"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apelido", models.CharField(max_length=100, verbose_name="Apelido")),
                (
                    "ultima_postagem",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Última Postagem"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Título")),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "arquivado",
                    models.BooleanField(default=False, verbose_name="Arquivado"),
                ),
                (
                    "data",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data do Cadastro"
                    ),
                ),
                (
                    "cadastrador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="temas",
                        to="perguntas.usuario",
                        verbose_name="Cadastrador Por",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=255, verbose_name="Resposta")),
                (
                    "data",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro da Resposta"
                    ),
                ),
                ("curtidas", models.IntegerField(default=0, verbose_name="Curtidas")),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="perguntas.pergunta",
                        verbose_name="Pergunta",
                    ),
                ),
                (
                    "cadastrador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="respostas",
                        to="perguntas.usuario",
                        verbose_name="Cadastrado Por",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pergunta",
            name="cadastrador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perguntas",
                to="perguntas.usuario",
                verbose_name="Cadastrado Por",
            ),
        ),
    ]
