# Generated by Django 5.1.2 on 2025-01-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=155, verbose_name="Nome")),
                ("data", models.DateField(verbose_name="Data")),
                ("local", models.CharField(max_length=200, verbose_name="Local")),
            ],
        ),
        migrations.CreateModel(
            name="Ministrante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                ("link_curriculo", models.URLField(verbose_name="Link do Currículo")),
            ],
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
            ],
        ),
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data da Atividade")),
                ("hora", models.TimeField(verbose_name="Hora da Atividade")),
                ("local", models.CharField(max_length=255, verbose_name="Local")),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("capacidade", models.IntegerField(verbose_name="Capacidade")),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividades",
                        to="appeventos.evento",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "ministrante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atividades",
                        to="appeventos.ministrante",
                        verbose_name="Ministrante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data da Inscrição"
                    ),
                ),
                (
                    "presenca",
                    models.BooleanField(default=False, verbose_name="Presença"),
                ),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscricoes",
                        to="appeventos.atividade",
                        verbose_name="Atividade",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscricoes",
                        to="appeventos.participante",
                        verbose_name="Participante",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inscrições",
            },
        ),
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data do Certificado"
                    ),
                ),
                (
                    "inscricao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appeventos.inscricao",
                        verbose_name="Inscrição",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.IntegerField(verbose_name="Nota")),
                ("comentario", models.TextField(verbose_name="Comentário")),
                (
                    "inscricao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appeventos.inscricao",
                        verbose_name="Inscrição",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="atividade",
            name="participantes",
            field=models.ManyToManyField(
                related_name="atividades",
                through="appeventos.Inscricao",
                to="appeventos.participante",
            ),
        ),
    ]
