# Generated by Django 5.1.2 on 2025-01-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeventos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avaliacao",
            options={"verbose_name_plural": "Avaliações"},
        ),
        migrations.AddField(
            model_name="atividade",
            name="tipo",
            field=models.CharField(
                choices=[("MI", "Minicurso"), ("PR", "Palestra"), ("OF", "Oficina")],
                default="MI",
                max_length=2,
                verbose_name="Tipo de Atividade",
            ),
        ),
    ]
