# Generated by Django 5.1.2 on 2025-01-31 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeventos", "0002_alter_avaliacao_options_atividade_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividade",
            name="ministrante",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atividades",
                to="appeventos.ministrante",
                verbose_name="Ministrante",
            ),
        ),
        migrations.AlterField(
            model_name="atividade",
            name="tipo",
            field=models.CharField(
                choices=[("OF", "Oficina"), ("PR", "Palestra"), ("MI", "Minicurso")],
                default="OF",
                max_length=20,
                verbose_name="Tipos",
            ),
        ),
    ]
