# Generated by Django 5.1.2 on 2025-02-13 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeventos", "0003_alter_atividade_ministrante_alter_atividade_tipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participante",
            name="email",
        ),
        migrations.AddField(
            model_name="participante",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="participantes/", verbose_name="Foto"
            ),
        ),
        migrations.AddField(
            model_name="participante",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participante",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
